[Interface]
Address = 10.2.0.2/32, 2a07:b944::2:2/128
DNS = 10.2.0.1, 2a07:b944::2:1
PrivateKey = MPR/mALbqphmRIMNQ9rKPwCmtuCWqE31Ii/kh2USv3g=

[Peer]
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 185.180.222.89:51820
PublicKey = qcb7KUuClTqMcsDxhDY3N5OnoW1twENuSw39kU8XiTU=
